name: Github Actions CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - githubactions*
      - feature/**
      - fix/**
      - pr/**

jobs:
  posix:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "TOOLSET=gcc COMPILER=g++-7 CXXSTD=11 Job 0"
            buildtype: "boost"
            packages: "g++-7 g++-9 clang-7 clang-10 libopenblas-base rpm2cpio cpio clinfo opencl-headers ocl-icd-opencl-dev"
            packages_to_remove: ""
            os: "ubuntu-18.04"
            cxx: "g++-7"
            sources: ""
            llvm_os: "bionic"
            llvm_ver: "10"
            toolset: "gcc"
            compiler: "g++-7"
            cxxstd: "11"
          - name: "TOOLSET=gcc COMPILER=g++-7 CXXSTD=17 Job 1"
            buildtype: "boost"
            packages: "g++-7 g++-9 clang-7 clang-10 libopenblas-base rpm2cpio cpio clinfo opencl-headers ocl-icd-opencl-dev"
            packages_to_remove: ""
            os: "ubuntu-18.04"
            cxx: "g++-7"
            sources: ""
            llvm_os: "bionic"
            llvm_ver: "10"
            toolset: "gcc"
            compiler: "g++-7"
            cxxstd: "17"
          - name: "TOOLSET=gcc COMPILER=g++-9 CXXSTD=2a Job 2"
            buildtype: "boost"
            packages: "g++-7 g++-9 clang-7 clang-10 libopenblas-base rpm2cpio cpio clinfo opencl-headers ocl-icd-opencl-dev"
            packages_to_remove: ""
            os: "ubuntu-18.04"
            cxx: "g++-9"
            sources: ""
            llvm_os: "bionic"
            llvm_ver: "10"
            toolset: "gcc"
            compiler: "g++-9"
            cxxstd: "2a"
          - name: "TOOLSET=clang COMPILER=clang++-7 CXXSTD=17 Job 3"
            buildtype: "boost"
            packages: "g++-7 g++-9 clang-7 clang-10 libopenblas-base rpm2cpio cpio clinfo opencl-headers ocl-icd-opencl-dev"
            packages_to_remove: ""
            os: "ubuntu-18.04"
            cxx: "clang++-7"
            sources: ""
            llvm_os: "bionic"
            llvm_ver: "10"
            toolset: "clang"
            compiler: "clang++-7"
            cxxstd: "17"
          - name: "TOOLSET=clang COMPILER=clang++-10 CXXSTD=2a Job 4"
            buildtype: "boost"
            packages: "g++-7 g++-9 clang-7 clang-10 libopenblas-base rpm2cpio cpio clinfo opencl-headers ocl-icd-opencl-dev"
            packages_to_remove: ""
            os: "ubuntu-18.04"
            cxx: "clang++-10"
            sources: ""
            llvm_os: "bionic"
            llvm_ver: "10"
            toolset: "clang"
            compiler: "clang++-10"
            cxxstd: "2a"

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - name: Check if running in container
        if: matrix.container != ''
        run: echo "GHA_CONTAINER=${{ matrix.container }}" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: linux
        shell: bash
        env:
          CXX: ${{ matrix.cxx }}
          SOURCES: ${{ matrix.sources }}
          LLVM_OS: ${{ matrix.llvm_os }}
          LLVM_VER: ${{ matrix.llvm_ver }}
          PACKAGES: ${{ matrix.packages }}
          PACKAGES_TO_REMOVE: ${{ matrix.packages_to_remove }}
          JOB_BUILDTYPE: ${{ matrix.buildtype }}
          TOOLSET: ${{ matrix.toolset }}
          COMPILER: ${{ matrix.compiler }}
          CXXSTD: ${{ matrix.cxxstd }}
          TRAVIS_BRANCH: ${{ github.base_ref }}
          TRAVIS_OS_NAME: "linux"
        run: |
          echo '==================================> SETUP'
          echo '==================================> PACKAGES'
          set -e
          if [ -n "$PACKAGES_TO_REMOVE" ]; then sudo apt-get purge -y $PACKAGES_TO_REMOVE; fi
          echo ">>>>> APT: REPO.."
          for i in {1..3}; do sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test" && break || sleep 2; done
          
          if test -n "${LLVM_OS}" ; then
              wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
              if test -n "${LLVM_VER}" ; then
                  sudo -E apt-add-repository "deb http://apt.llvm.org/${LLVM_OS}/ llvm-toolchain-${LLVM_OS}-${LLVM_VER} main"
              else
                  # Snapshot (i.e. trunk) build of clang
                  sudo -E apt-add-repository "deb http://apt.llvm.org/${LLVM_OS}/ llvm-toolchain-${LLVM_OS} main"
              fi
          fi
          echo ">>>>> APT: UPDATE.."
          sudo -E apt-get -o Acquire::Retries=3 update
          if test -n "${SOURCES}" ; then
              echo ">>>>> APT: INSTALL SOURCES.."
              for SOURCE in $SOURCES; do
                  sudo -E apt-add-repository ppa:$SOURCE
              done
          fi
          echo ">>>>> APT: INSTALL ${PACKAGES}.."
          sudo -E DEBIAN_FRONTEND=noninteractive apt-get -o Acquire::Retries=3 -y --no-install-suggests --no-install-recommends install ${PACKAGES}

          echo '==================================> INSTALL AND COMPILE'
          set -e
          set -x
          export TRAVIS_BUILD_DIR=$(pwd)
          export TRAVIS_BRANCH=${TRAVIS_BRANCH:-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')}
          export VCS_COMMIT_ID=$GITHUB_SHA
          export GIT_COMMIT=$GITHUB_SHA
          export REPO_NAME=$(basename $GITHUB_REPOSITORY)
          export USER=$(whoami)
          export CC=${CC:-gcc}
          export PATH=~/.local/bin:/usr/local/bin:$PATH
          export CLBLAS_PREFIX="${TRAVIS_BUILD_DIR}/CLBLAS/"
          export PATH="${CLBLAS_PREFIX}/bin:$PATH"
          export LD_LIBRARY_PATH="${CLBLAS_PREFIX}/lib:$LD_LIBRARY_PATH"

          if [ "$JOB_BUILDTYPE" == "boost" ]; then

          echo '==================================> INSTALL'

          if [ ${TRAVIS_OS_NAME} == "linux" ]; then .ci/install-ocl-ubuntu.sh; fi
          .ci/install-clblas.sh
          cmake --version;
          ${CC} --version || true;
          ${CXX} --version;
          cd ..
          git clone -b master --depth 1 https://github.com/boostorg/boost.git boost-root
          cd boost-root
          git submodule update --init --jobs 8 tools/build
          git submodule update --init --jobs 8 libs/config
          git submodule update --init --jobs 8 tools/boostdep
          mkdir -p libs/numeric/
          cp -rp $TRAVIS_BUILD_DIR/. libs/numeric/ublas
          python tools/boostdep/depinst/depinst.py -I benchmarks numeric/ublas
          ./bootstrap.sh
          ./b2 -j 8 headers
          export BOOST_ROOT="`pwd`"

          echo '==================================> SCRIPT'

          echo "using $TOOLSET : : $COMPILER ;" >> ~/user-config.jam;
          echo "using clblas : : <include>${CLBLAS_PREFIX}/include <search>${CLBLAS_PREFIX}/lib ;" >> ~/user-config.jam;
          cp $TRAVIS_BUILD_DIR/opencl.jam ~/
          cp $TRAVIS_BUILD_DIR/clblas.jam ~/
          cd libs/numeric/ublas
          $BOOST_ROOT/b2 -j 8 test toolset=$TOOLSET cxxstd=$CXXSTD

          fi
